# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Assignment2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: GitHub Action for Yarn
      # You may pin to the exact commit or the version.
      # uses: Borales/actions-yarn@4965e1a0f0ae9c422a9a5748ebd1fb5e097d22b9
      uses: Borales/actions-yarn@v2.3.0
      with:
        # Yarn command
        cmd: install
    
    - name: creating build
      run: yarn build
    
    - name: installing surge
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://assignriz.surge.sh/ --token ${{secrets.MY_KEY}}
